apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:            
            - labelSelector:
                matchExpressions:
                 - key: app
                   operator: In
                   values:
                   - apache
              topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                     - apache-node
      containers:
        - name: apache
          image: ripken/apache2-practice:3.3
          ports:
           - name: http
             containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: apache
spec:
  type: NodePort
  selector:
    app: apache
  ports:
    - protocol: TCP
      nodePort: 31000
      port: 80
      targetPort: http